retail_pipeline_profile:
  outputs:
    dev:
      type: clickhouse
      host: clickhouse
      port: 8123
      user: "{{ env_var('CLICKHOUSE_USER') }}"
      password: "{{ env_var('CLICKHOUSE_PASSWORD') }}"
      schema: "{{ env_var('CLICKHOUSE_DB') }}"
  target: dev

